rbtname: inverted_pendulum

system: # 机器人系统参数
  GRAV: -9.8    # 重力加速度
  TSf: 0.002   # time step in float
  Tend: 1000   # 测试时间 second
  root_path: "./envs"
  mjcf_path: "/inverted_pendulum.xml"
  log_path: &log_path
    dir: ../log/Cassie/${now:%Y-%m-%d}/${now:%H-%M-%S}
  visual: True
  render_resolution: [1920, 1080]
  dynamics_randomization: True

env:
  num_envs: 16
  time_limit: 600  # 最大600个step

commands:
  lin_vel_x:        [0.4, 0.7]
  lin_vel_y:        [0.0, 0.0]
  ang_vel_yaw:      [-1.0, 1.0]

init_state:
  pos: [0.0, 0.0]

control:
  # PD Drive parameters:
  P: [100.0, 100.0]
  D: [ 10.0,  10.0]
  # action scale: target angle = actionScale * action + defaultAngle
  action_scale: 0.5
  # decimation: Number of control action updates @ sim DT per policy DT
  decimation: 1

rewards:
  omega: 0.5
  scales:
    ref:    0.1
    spring: 0.1
    ori:    0.1
    vel:    0.1
    termin: 0.1
